app/Http/routes.php
<?php

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('reset/sent', function () {
    return View('auth.sent');
});

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => 'auth'], function () {
    Route::any('/profile/remove', ['as' => 'removeAvatar', 'uses' => 'UsersController@removeAvatar']);

    Route::get('/', 'HomeController@getFeed');
    Route::get('/home/{filter}/{param?}', 'HomeController@getFeed');

    Route::post('form1', ['as' => 'form1', 'uses' => 'FormsController@form1']);
    Route::post('form2', ['as' => 'form2', 'uses' => 'FormsController@form2']);

    Route::get('group/{id}', 'HomeController@getGroup');
    Route::get('category/{id}', ['as' => 'category', 'uses' => 'CategoriesController@show']);
    Route::get('ajax/tags', 'Ajax\TagsController@getList');

    Route::get('search', 'SearchController@search');

    Route::resource('posts', 'PostsController', ['except' => 'destroy']);
    Route::get('posts/read/{id}', 'PostsController@read');
    Route::get('posts/star/{id}', 'PostsController@star');
    Route::post('comment', 'PostsController@comment');
    Route::get('comments/delete/{id}', 'PostsController@deleteComment');

    Route::get('profile', 'UsersController@getProfile');
    Route::post('profile', 'UsersController@postProfile');

    Route::get('article/{id}', ['as' => 'article', 'uses' => 'ArticlesController@show']);
    Route::get('articles/deleteImage/{id}', 'ArticlesController@deleteImage');
    Route::get('posts/deleteImage/{id}', 'PostsController@deleteImage');
    Route::any('posts/deleteown/{id}', 'PostsController@delete');

    Route::get('support', function () {
        view()->share('view', 'support');
        view()->share('active', 'support');

        return View('pages.support');
    });

    Route::get('files/download/{id}', ['as' => 'downloadFile', 'uses' => 'FilesController@download']);
});

Route::group(['prefix' => 'ajax', 'middleware' => 'auth'], function () {
    Route::post('post', 'Ajax\PostsController@create');
    Route::post('uploadImage', 'Ajax\FileController@uploadImage');
    Route::post('uploadFile', 'Ajax\FileController@uploadFile');
});

Route::group(['middleware' => ['auth', 'auth.admin']], function () {
    Route::any('posts/delete/{id}', ['as' => 'deletePost', 'uses' => 'PostsController@destroy']);
    Route::any('users/delete/{id}', ['as' => 'deleteUser', 'uses' => 'UsersController@destroy']);
    Route::any('tags/delete/{id}', ['as' => 'deleteTag', 'uses' => 'TagsController@destroy']);
    Route::any('categories/delete/{id}', ['as' => 'deleteCategory', 'uses' => 'CategoriesController@destroy']);
    Route::any('categories/up/{id}', ['as' => 'upCategory', 'uses' => 'CategoriesController@up']);
    Route::any('categories/down/{id}', ['as' => 'downCategory', 'uses' => 'CategoriesController@down']);
    Route::any('articles/delete/{id}', ['as' => 'deleteArticle', 'uses' => 'ArticlesController@destroy']);

    Route::resource('articles', 'ArticlesController', ['except' => 'show']);
    Route::resource('branches', 'BranchesController', ['except' => 'show']);
    Route::resource('groups', 'GroupsController', ['except' => 'show']);
    Route::resource('tags', 'TagsController', ['except' => 'show']);
    Route::resource('users', 'UsersController', ['except' => 'show']);
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);

    Route::get('files/delete/{id}', ['as' => 'deleteFile', 'uses' => 'FilesController@delete']);

    Route::get('statistic', ['as' => 'statistic', 'uses' => 'StatisticController@index']);
    Route::get('statistic/{post}', ['as' => 'statistic.show', 'uses' => 'StatisticController@show']);
});

app/Http/Controllers/Ajax/TagsController.php
<?php namespace App\Http\Controllers\Ajax;

use App\Ck\Models\Tag;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Request;

class TagsController extends Controller {

    public function getList()
    {
        return response()->json(
            Tag::where('title', 'LIKE', '%' . Request::input('term') . '%')->orderBy('title')->lists('title', 'id')
        );
    }

}

app/Http/Controllers/TagsController.php
<?php namespace App\Http\Controllers;

use App\Ck\Models\Tag;
use App\Http\Requests\TagsRequest;

class TagsController extends Controller
{
    public function __construct()
    {
        parent::__construct();
        view()->share('active', 'tags');
    }

    public function index()
    {
        view()->share('view', 'tags-list');

        $items = Tag::orderBy('title', 'ASC')->paginate(20);
        return View('tags.index', compact('items'));
    }

    public function create()
    {
        view()->share('view', 'tags-create');

        $item = new Tag();
        return View('tags.form', compact('item'));
    }

    public function store(TagsRequest $request)
    {
        Tag::create($request->all());
        return redirect('tags');
    }

    public function edit($id)
    {
        view()->share('view', 'tags-edit');

        $item = Tag::find($id);
        return View('tags.form', compact('item'));
    }

    public function update(TagsRequest $request, $id)
    {
        $item = Tag::findOrFail($id);
        $item->update($request->all());
        return redirect('tags');
    }

    public function destroy($id)
    {
        Tag::findOrFail($id)->delete();
        return redirect('tags');
    }

}

resources/views/tags/form.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                @if ($item->id)
                    {!! Form::model($item, ['route' => ['tags.update', $item->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
                @else
                    {!! Form::model($item, ['route' => 'tags.store', 'class' => 'form-horizontal']) !!}
                @endif
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            {!! Form::label('title', trans('labels.title'), ['class' => 'col-md-2 control-label']) !!}
                            <div class="col-md-10">
                                {!! Form::text('title', $item->title, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">
                                {!! Form::button(trans('buttons.save'), ['type' => 'submit', 'class' => 'btn btn-primary']) !!}
                                {!! link_to_route('tags.index', trans('buttons.close'), null, ['class' => 'btn btn-danger']) !!}
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <a href="{{ route('tags.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> {{ trans('buttons.new') }}</a>
                    </div>
                    <div class="col-sm-12 table-responsive m-t-20">
                        <table class="table table-bordered table-hover m-0">
                            <tr>
                                <th>{{ trans('labels.title') }}</th>
                                <th>{{ trans('labels.edit') }}</th>
                                <th>{{ trans('labels.delete') }}</th>
                            </tr>
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $item->title }}</td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="{!! route('tags.edit', ['id' => $item->id]) !!}"><i class="fa fa-edit"></i></a>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="#" data-href="{!! route('deleteTag', ['id' => $item->id]) !!}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-remove"></i></a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3">{{ trans('messages.list_empty') }}</td>
                                </tr>
                            @endforelse
                        </table>
                    </div>
                    <div class="col-sm-12 text-center">
                        {!! $items->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-sm" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    {{ trans('messages.delete_confirmation') }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('buttons.no') }}</button>
                    <a class="btn btn-danger btn-ok">{{ trans('buttons.yes') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#confirm-delete').on('show.bs.modal', function(e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
@endsection