app/Http/routes.php
<?php

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('reset/sent', function () {
    return View('auth.sent');
});

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => 'auth'], function () {
    Route::any('/profile/remove', ['as' => 'removeAvatar', 'uses' => 'UsersController@removeAvatar']);

    Route::get('/', 'HomeController@getFeed');
    Route::get('/home/{filter}/{param?}', 'HomeController@getFeed');

    Route::post('form1', ['as' => 'form1', 'uses' => 'FormsController@form1']);
    Route::post('form2', ['as' => 'form2', 'uses' => 'FormsController@form2']);

    Route::get('group/{id}', 'HomeController@getGroup');
    Route::get('category/{id}', ['as' => 'category', 'uses' => 'CategoriesController@show']);
    Route::get('ajax/tags', 'Ajax\TagsController@getList');

    Route::get('search', 'SearchController@search');

    Route::resource('posts', 'PostsController', ['except' => 'destroy']);
    Route::get('posts/read/{id}', 'PostsController@read');
    Route::get('posts/star/{id}', 'PostsController@star');
    Route::post('comment', 'PostsController@comment');
    Route::get('comments/delete/{id}', 'PostsController@deleteComment');

    Route::get('profile', 'UsersController@getProfile');
    Route::post('profile', 'UsersController@postProfile');

    Route::get('article/{id}', ['as' => 'article', 'uses' => 'ArticlesController@show']);
    Route::get('articles/deleteImage/{id}', 'ArticlesController@deleteImage');
    Route::get('posts/deleteImage/{id}', 'PostsController@deleteImage');
    Route::any('posts/deleteown/{id}', 'PostsController@delete');

    Route::get('support', function () {
        view()->share('view', 'support');
        view()->share('active', 'support');

        return View('pages.support');
    });

    Route::get('files/download/{id}', ['as' => 'downloadFile', 'uses' => 'FilesController@download']);
});

Route::group(['prefix' => 'ajax', 'middleware' => 'auth'], function () {
    Route::post('post', 'Ajax\PostsController@create');
    Route::post('uploadImage', 'Ajax\FileController@uploadImage');
    Route::post('uploadFile', 'Ajax\FileController@uploadFile');
});

Route::group(['middleware' => ['auth', 'auth.admin']], function () {
    Route::any('posts/delete/{id}', ['as' => 'deletePost', 'uses' => 'PostsController@destroy']);
    Route::any('users/delete/{id}', ['as' => 'deleteUser', 'uses' => 'UsersController@destroy']);
    Route::any('tags/delete/{id}', ['as' => 'deleteTag', 'uses' => 'TagsController@destroy']);
    Route::any('categories/delete/{id}', ['as' => 'deleteCategory', 'uses' => 'CategoriesController@destroy']);
    Route::any('categories/up/{id}', ['as' => 'upCategory', 'uses' => 'CategoriesController@up']);
    Route::any('categories/down/{id}', ['as' => 'downCategory', 'uses' => 'CategoriesController@down']);
    Route::any('articles/delete/{id}', ['as' => 'deleteArticle', 'uses' => 'ArticlesController@destroy']);

    Route::resource('articles', 'ArticlesController', ['except' => 'show']);
    Route::resource('branches', 'BranchesController', ['except' => 'show']);
    Route::resource('groups', 'GroupsController', ['except' => 'show']);
    Route::resource('tags', 'TagsController', ['except' => 'show']);
    Route::resource('users', 'UsersController', ['except' => 'show']);
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);

    Route::get('files/delete/{id}', ['as' => 'deleteFile', 'uses' => 'FilesController@delete']);

    Route::get('statistic', ['as' => 'statistic', 'uses' => 'StatisticController@index']);
    Route::get('statistic/{post}', ['as' => 'statistic.show', 'uses' => 'StatisticController@show']);
});

app/Http/Controllers/Ajax/PostsController.php
<?php namespace App\Http\Controllers\Ajax;

use Auth;
use App\Ck\Helpers\AccessHelper;
use App\Ck\Helpers\TagsHelper;
use App\Ck\Models\Post;
use App\Http\Controllers\Controller;
use App\Http\Requests\AjaxPostRequest;
use Illuminate\Support\Facades\Storage;

class PostsController extends Controller {

    public function create(AjaxPostRequest $request)
    {
        $user = Auth::user();

        $data = [
            'title' => $request->input('title'),
            'lead'  => $request->input('lead'),
            'state' => 1
        ];

        if (!empty($request->input('image'))) {
            $image = $request->input('image');

            Storage::move('temp/'.$image, 'images/'.$image);
            $data['image'] = $image;
        }

        $item = Post::create($data);

        if (!empty($request->input('tags'))) {
            TagsHelper::processModelTags($item, $request->input('tags'));
        }

        $groups = AccessHelper::filterUserGroups($request->input('groups'));

        if (count($groups)) {
            $item->groups()->sync($groups);
        } else {
            $item->groups()->sync(AccessHelper::allUserGroups());
        }

        $item->branches()->sync([$user->branch_id]);

        return response()->json(['message' => url('/')]);
    }

}

app/Http/Controllers/PostsController.php
<?php namespace App\Http\Controllers;

use DB;
use Auth;
use App\Ck\Helpers\AccessHelper;
use App\Ck\Models\Comment;
use App\Ck\Models\Post;
use Illuminate\Http\Request;
use App\Ck\Requests\PostRequest;
use App\Ck\Requests\CommentRequest;
use Illuminate\Support\Facades\Storage;

class PostsController extends Controller
{
    protected $isAdmin;

    protected $isEditor;

    public function __construct()
    {
        parent::__construct();

        $this->middleware('auth');
        $this->middleware('auth.editor', ['only' => ['index', 'destroy']]);

        $this->isAdmin = AccessHelper::isSuperAdmin();
        $this->isEditor = AccessHelper::isAdmin();

        view()->share('active', 'posts');
    }

    public function index(Request $request)
    {
        view()->share('view', 'posts-list');

        $filter_groups = [
                '' => trans('labels.select_group')] +
            \App\Ck\Models\Group::whereNotIn('id', [1, 2])->lists('title', 'id')->toArray();
        $filter_branches = [
                '' => trans('labels.select_branch')] +
            \App\Ck\Models\Branch::lists('title', 'id')->toArray();

        $filters = [
            'group'  => $request->input('filter_group'),
            'branch' => $request->input('filter_branch'),
            'search' => $request->input('filter_search')
        ];

        $query = new Post();

        if ($filters['group']) {
            $post_ids = DB::table('group_posts')
                          ->select('post_id')
                          ->where('group_id', $filters['group'])
                          ->lists('post_id');

            $query = $query->whereIn('id', $post_ids);
        } else {
            $filters['group'] = 0;
        }

        if ($filters['branch'] > 0) {
            $post_ids = DB::table('branch_posts')
                          ->select('post_id')
                          ->where('branch_id', $filters['branch'])
                          ->lists('post_id');

            $query = $query->whereIn('id', $post_ids);
        } else {
            $filters['branch'] = 0;
        }

        if (!empty($filters['search'])) {
            $query = $query->where(function ($q) use ($filters) {
                $q->where('posts.title', 'LIKE', '%' . $filters['search'] . '%');
            });
        }

        $isAdmin = $this->isAdmin;
        $isEditor = $this->isEditor;

        if (!$this->isAdmin) {
            $query = $query->whereCreatedBy(Auth::user()->id);
        }

        $items = $query->orderBy('created_at', 'DESC')->paginate(20);

        return View(
            'posts.index',
            compact('items', 'isAdmin', 'isEditor', 'filter_groups', 'filter_branches', 'filters')
        );
    }

    public function create()
    {
        view()->share('active', '');
        view()->share('view', 'posts-create');

        $item = new Post();
        $active = '';
        $branches = [];
        $groups = [];
        $available_branches = AccessHelper::availableBranches();
        $available_groups = AccessHelper::groupsForPosting();

        if ((count($available_branches) == 0) && (count($available_groups) == 0)) {
            return redirect('/');
        }

        return View(
            'posts.form',
            compact('item', 'active', 'groups', 'branches', 'available_branches', 'available_groups')
        );
    }

    public function store(PostRequest $request)
    {
        $data = $request->all();

        $data['state'] = isset($data['state']) ? 1 : 0;
        $data['must_read'] = isset($data['must_read']) ? 1 : 0;

        $item = Post::create($data);

        if (!empty($data['image'])) {
            Storage::move('temp/' . $data['image'], 'images/' . $data['image']);
        }

        foreach ($request->input('files', []) as $file) {
            \App\Ck\Models\File::find($file)->update(['post_id' => $item->id]);
        }

        if (!isset($data['groups']) || ($data['active'] == 'branch')) {
            $data['groups'] = [];
        }

        if (!isset($data['branches']) || ($data['active'] == 'group')) {
            $data['branches'] = [];
        }

        if (!isset($data['tags'])) {
            $data['tags'] = [];
        }

        $item->groups()->sync($data['groups']);
        $item->branches()->sync($data['branches']);
        $item->tags()->sync($data['tags']);

        return redirect('posts');
    }

    public function edit($id)
    {
        $item = Post::find($id);
        $active = '';

        if (count($item->groups)) {
            $active = 'group';
        } elseif (count($item->branches)) {
            $active = 'branch';
        }

        if (AccessHelper::canEditPost($item)) {
            view()->share('view', 'posts-edit');

            $branches = [];
            $groups = [];

            foreach ($item->branches as $branch) {
                $branches[] = $branch->id;
            }

            foreach ($item->groups as $group) {
                $groups[] = $group->id;
            }

            $available_branches = AccessHelper::availableBranches();
            $available_groups = AccessHelper::groupsForPosting();

            return View(
                'posts.form',
                compact('item', 'active', 'groups', 'branches', 'available_branches', 'available_groups')
            );
        }

        return redirect('/');
    }

    public function update($id, PostRequest $request)
    {
        $data = $request->all();

        $data['state'] = isset($data['state']) ? 1 : 0;
        $data['must_read'] = isset($data['must_read']) ? 1 : 0;

        if (!isset($data['groups']) || ($data['active'] == 'branch')) {
            $data['groups'] = [];
        }

        if (!isset($data['branches']) || ($data['active'] == 'group')) {
            $data['branches'] = [];
        }

        if (!isset($data['tags'])) {
            $data['tags'] = [];
        }

        $item = Post::find($id);

        if (AccessHelper::canEditPost($item)) {
            if ($item->image != $data['image']) {
                Storage::move('temp/' . $data['image'], 'images/' . $data['image']);
                if (!empty($item->image) && Storage::has('images/' . $item->image)) {
                    Storage::delete('images/' . $item->image);
                }
            }

            $item->update($data);

            foreach ($request->input('files', []) as $file) {
                \App\Ck\Models\File::find($file)->update(['post_id' => $item->id]);
            }

            $item->groups()->sync($data['groups']);
            $item->branches()->sync($data['branches']);
            $item->tags()->sync($data['tags']);

            return redirect('posts');
        }

        return redirect('/');
    }

    public function show($id)
    {
        $item = Post::find($id);

        if (AccessHelper::canAccessPost($item)) {
            view()->share('active', '');
            view()->share('view', 'post');

            return View('posts.show', compact('item'));
        }

        return redirect('/');
    }

    public function comment(CommentRequest $request)
    {
        if (!AccessHelper::canAccessPost(Post::find($request->input('post_id')))) {
            return redirect('/');
        }

        if (!empty($request->input('comment_id'))) {
            $comment = Comment::find($request->input('comment_id'));
            $comment->comment = $request->input('comment');
            $comment->update();

            return redirect('posts/' . $comment->post_id);
        }

        $data = [
            'post_id' => $request->input('post_id'),
            'user_id' => \Auth::user()->id,
            'comment' => $request->input('comment'),
        ];

        Comment::create($data);

        return redirect('posts/' . $data['post_id']);
    }

    public function deleteComment($id)
    {
        $comment = Comment::find($id);
        $post_id = $comment->post_id;

        if ($comment->user_id == Auth::user()->id) {
            $comment->delete();
        }

        return redirect('posts/' . $post_id);
    }

    public function read($id)
    {
        $user = Auth::user();
        $item = Post::find($id);

        if (!$item->read->contains($user->id)) {
            $item->read()->attach($user->id);
        }

        return redirect('/');
    }

    public function star($id)
    {
        $user = Auth::user();
        $item = Post::find($id);

        if ($item->star->contains($user->id)) {
            $item->star()->detach($user->id);
        } else {
            $item->star()->attach($user->id);
        }

        return redirect()->back();
    }

    public function delete($id)
    {
        if (AccessHelper::isAdmin()) {
            $post = Post::find($id);
            if ($post->created_by == Auth::user()->id) {
                Post::find($id)->delete();

                return redirect('/');
            }
        }

        return redirect()->back();
    }

    public function destroy($id)
    {
        Post::find($id)->delete();

        return redirect()->back();
    }

    public function deleteImage($id)
    {
        $item = Post::find($id);

        if (!empty($item->image)) {
            if (Storage::has('images/' . $item->image)) {
                Storage::delete('images/' . $item->image);
            }
            $item->image = null;
            $item->save();
        }

        return redirect('posts/' . $item->id . '/edit');
    }

}

resources/views/posts/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    @if ($isAdmin)
                        {!! Form::open(['method' => 'GET', 'id' => 'filter-form']) !!}
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    {!! Form::text('filter_search', $filters['search'], ['class' => 'form-control', 'placeholder' => trans('labels.search')]) !!}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    {!! Form::select('filter_group', $filter_groups, $filters['group'], ['v-model' => 'group', 'class' => 'form-control']) !!}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    {!! Form::select('filter_branch', $filter_branches, $filters['branch'], ['v-model' => 'branch', 'class' => 'form-control']) !!}
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    {!! Form::button(trans('buttons.filter'), ['class' => 'btn btn-primary', 'type' => 'submit']) !!}
                                    <a href="{{ route('posts.create') }}" class="btn btn-primary pull-right"><i
                                                class="fa fa-plus"></i> {{ trans('buttons.new') }}</a>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    @else
                        <a href="{{ route('posts.create') }}" class="btn btn-primary pull-right"><i
                                    class="fa fa-plus"></i> {{ trans('buttons.new') }}</a>
                        <div class="clearfix"></div>
                    @endif
                    <div class="col-sm-12 table-responsive m-t-20">
                        <table class="table table-bordered table-hover m-0">
                            <tr>
                                <th>{{ trans('labels.title') }}</th>
                                <th>{{ trans('labels.group') }}</th>
                                <th>{{ trans('labels.author') }}</th>
                                <th>{{ trans('labels.created') }}</th>
                                <th class="uk-text-center">{{ trans('labels.status') }}</th>
                                <th>{{ trans('labels.edit') }}</th>
                                <th>{{ trans('labels.delete') }}</th>
                            </tr>
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $item->title }}</td>
                                    <td>
                                        @foreach ($item->groups as $group)
                                            <div class="label label-pink">{{ $group->title }}</div>
                                        @endforeach
                                        @foreach ($item->branches as $branch)
                                            <div class="label label-info">{{ $branch->title }}</div>
                                        @endforeach
                                    </td>
                                    <td width="1%" nowrap>{{ @$item->author->name }}</td>
                                    <td width="1%" nowrap>{{ $item->created_at }}</td>
                                    <td class="uk-text-center" width="1%" nowrap>
                                        <div class="label label-{{ ($item->state == 1)?'default':'pink' }}">{{ ($item->state == 1)?trans('labels.published'):trans('labels.unpublished') }}</div>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="{!! route('posts.edit', ['id' => $item->id]) !!}"><i
                                                    class="fa fa-edit"></i></a>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="#" data-href="{!! route('deletePost', ['id' => $item->id]) !!}"
                                           data-toggle="modal" data-target="#confirm-delete"><i
                                                    class="fa fa-remove"></i></a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7">{{ trans('messages.list_empty') }}</td>
                                </tr>
                            @endforelse
                        </table>
                    </div>
                    <div class="col-sm-12 text-center">
                        {!! $items->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-sm" id="confirm-delete" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    {{ trans('messages.delete_confirmation') }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">{{ trans('buttons.no') }}</button>
                    <a class="btn btn-danger btn-ok">{{ trans('buttons.yes') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    {!! Html::script('js/vue.js') !!}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#confirm-delete').on('show.bs.modal', function (e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
        @if ($isAdmin)
            new Vue({
                el: '#filter-form',
                data: {
                    group: {{ $filters['group'] }},
                    branch: {{ $filters['branch'] }}
                },
                watch: {
                    'group': function (val) {
                        if (val > 0) {
                            this.branch = 0;
                        }
                    },
                    'branch': function (val) {
                        if (val > 0) {
                            this.group = 0;
                        }
                    }
                }
            });
        @endif
    </script>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.main')
<?php
$btn_class = '';
if (count($item->branches) > 0) {
    $tmp_item = \App\Ck\Models\Post::find($item->id);
    if ($tmp_item->branches()->where('id', 1)->count()) {
        $btn_class = 'btn-primary';
    } else {
        $btn_class = 'btn-info';
    }
} else if (count($item->groups) > 0) {
    $btn_class = 'btn-pink';
}
?>
@section('content')
    <?php $user_id = Auth::user()->id; ?>
    <?php $star_active = $item->star->contains($user_id); ?>
    <div class="row" style="max-width: 934px;">
        <div class="col-md-12">
            <div class="card-box p-0">
                @if(!empty($item->image))
                    {!! ImageHelper::responsiveImage($item->image) !!}
                @endif
                <div class="relative post-content">
                    <a href="{{ url('posts/star/'.$item->id) }}"
                    class="btn-star star-relative star-smaller {{ ($star_active)?'star-active':'' }}"><i
                        class="ion-ios7-star"></i></a>
                    @if ($item->must_read && !$item->read->contains($user_id))
                        <div class="must-read btn {{ $btn_class }} btn-xs">{{ trans('labels.mustread') }}</div>
                    @endif
                    <span class="post-details">{{ trans('labels.written_by') }} {{ $item->author->name }} - {{ \Carbon\Carbon::createFromTimestamp(strtotime($item->created_at))->format('d.m.Y') }}</span>
                    <h1 class="post-title">{{ $item->title }}</h1>
                    <h3 class="post-lead">{!! prepareLead($item->lead) !!}</h3>
                    <div class="post-text">
                        {!! prepareContent($item->content) !!}
                    </div>
                    <a href="#" class="btn btn-back"><i class="fa fa-angle-double-left"></i> {{ trans('buttons.back') }}</a>
                    @if ($item->must_read && !$item->read->contains($user_id))
                        <a href="{{ url('posts/read/'.$item->id) }}"
                           class="btn btn-primary">{{ trans('buttons.read') }}</a>
                    @endif
                    @if ($item->created_by == Auth::user()->id)
                        <a href="{{ route('posts.edit', ['id' => $item->id]) }}" class="btn btn-info">{{ trans('buttons.edit') }}</a>
                        @if (AccessHelper::isAdmin())
                            <a href="{{ url('posts/deleteown/'.$item->id) }}" class="btn btn-danger">{{ trans('buttons.delete') }}</a>
                        @endif
                    @endif
                </div>
            </div>
            @if (count($item->files))
                <h4><i class="fa fa-download"></i> {{ trans('labels.files') }}</h4>
                <div class="card-box">
                    <ul class="list-group m-b-0">
                        @foreach($item->files as $file)
                            <li class="list-group-item">
                                <a href="{{ url('files/download/' . $file->id) }}">{{ $file->original }}</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if ($item->groups()->count() > 0)
                <h4><i class="fa fa-comments-o"></i> {{ trans('labels.comments') }}</h4>
                <div class="card-box">
                    <div class="list-group m-b-0">
                        @forelse ($item->comments()->orderBy('created_at', 'ASC')->get() as $comment)
                            <div class="media">
                                <div class="media-left">
                                    {!! ImageHelper::userAvatarMedium($comment->user->avatar) !!}
                                </div>
                                <div class="media-body">
                                    <p class="comment-text">{{ $comment->comment }}</p>
                                    <p class="comment-details">{{ $comment->user->name }}
                                        , {{ Carbon::createFromTimeStamp(strtotime($comment->created_at))->diffForHumans() }}
                                        @if ($comment->user->id == $user_id)
                                            |
                                            <a href="" class="edit-comment" data-attr="{{ $comment->id }}" data-text="{{ $comment->comment }}">{{ trans('buttons.edit') }}</a>
                                            |
                                            <a href="{{ url('comments/delete/'.$comment->id) }}">{{ trans('buttons.delete') }}</a>
                                        @endif
                                    </p>

                                </div>
                            </div>
                        @empty
                            <p class="m-b-0">{{ trans('messages.comment_first') }}</p>
                        @endforelse
                    </div>
                </div>
                <div class="card-box">
                    {!! Form::open(['url' => url('comment'), 'method' => 'POST']) !!}
                    <div class="form-group">
                        {!! Form::textarea('comment', null, ['class' => 'form-control', 'style' => 'height: 75px; resize: none;']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::button(trans('buttons.comment'), ['type' => 'submit', 'class' => 'btn btn-primary']) !!}
                        {!! Form::button(trans('buttons.cancel'), ['id' => 'btn-cancel', 'class' => 'btn btn-danger hidden']) !!}
                    </div>
                    {!! Form::hidden('post_id', $item->id) !!}
                    {!! Form::hidden('comment_id', null) !!}
                    {!! Form::close() !!}
                </div>
            @endif
        </div>
    </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function(){
            $('a.edit-comment').on('click', function(ev){
                ev.preventDefault();
                $('textarea.form-control').val($(this).attr('data-text')).focus();
                $('input[name="comment_id"]').val($(this).attr('data-attr'));
                $('#btn-cancel').removeClass('hidden');
            });
            $('#btn-cancel').on('click', function(ev){
                ev.preventDefault();
                $('textarea.form-control').val('');
                $('input[name="comment_id"]').val('');
                $('#btn-cancel').addClass('hidden');
            });
        });
    </script>
@endsection