app/Http/routes.php
<?php

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('reset/sent', function () {
    return View('auth.sent');
});

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => 'auth'], function () {
    Route::any('/profile/remove', ['as' => 'removeAvatar', 'uses' => 'UsersController@removeAvatar']);

    Route::get('/', 'HomeController@getFeed');
    Route::get('/home/{filter}/{param?}', 'HomeController@getFeed');

    Route::post('form1', ['as' => 'form1', 'uses' => 'FormsController@form1']);
    Route::post('form2', ['as' => 'form2', 'uses' => 'FormsController@form2']);

    Route::get('group/{id}', 'HomeController@getGroup');
    Route::get('category/{id}', ['as' => 'category', 'uses' => 'CategoriesController@show']);
    Route::get('ajax/tags', 'Ajax\TagsController@getList');

    Route::get('search', 'SearchController@search');

    Route::resource('posts', 'PostsController', ['except' => 'destroy']);
    Route::get('posts/read/{id}', 'PostsController@read');
    Route::get('posts/star/{id}', 'PostsController@star');
    Route::post('comment', 'PostsController@comment');
    Route::get('comments/delete/{id}', 'PostsController@deleteComment');

    Route::get('profile', 'UsersController@getProfile');
    Route::post('profile', 'UsersController@postProfile');

    Route::get('article/{id}', ['as' => 'article', 'uses' => 'ArticlesController@show']);
    Route::get('articles/deleteImage/{id}', 'ArticlesController@deleteImage');
    Route::get('posts/deleteImage/{id}', 'PostsController@deleteImage');
    Route::any('posts/deleteown/{id}', 'PostsController@delete');

    Route::get('support', function () {
        view()->share('view', 'support');
        view()->share('active', 'support');

        return View('pages.support');
    });

    Route::get('files/download/{id}', ['as' => 'downloadFile', 'uses' => 'FilesController@download']);
});

Route::group(['prefix' => 'ajax', 'middleware' => 'auth'], function () {
    Route::post('post', 'Ajax\PostsController@create');
    Route::post('uploadImage', 'Ajax\FileController@uploadImage');
    Route::post('uploadFile', 'Ajax\FileController@uploadFile');
});

Route::group(['middleware' => ['auth', 'auth.admin']], function () {
    Route::any('posts/delete/{id}', ['as' => 'deletePost', 'uses' => 'PostsController@destroy']);
    Route::any('users/delete/{id}', ['as' => 'deleteUser', 'uses' => 'UsersController@destroy']);
    Route::any('tags/delete/{id}', ['as' => 'deleteTag', 'uses' => 'TagsController@destroy']);
    Route::any('categories/delete/{id}', ['as' => 'deleteCategory', 'uses' => 'CategoriesController@destroy']);
    Route::any('categories/up/{id}', ['as' => 'upCategory', 'uses' => 'CategoriesController@up']);
    Route::any('categories/down/{id}', ['as' => 'downCategory', 'uses' => 'CategoriesController@down']);
    Route::any('articles/delete/{id}', ['as' => 'deleteArticle', 'uses' => 'ArticlesController@destroy']);

    Route::resource('articles', 'ArticlesController', ['except' => 'show']);
    Route::resource('branches', 'BranchesController', ['except' => 'show']);
    Route::resource('groups', 'GroupsController', ['except' => 'show']);
    Route::resource('tags', 'TagsController', ['except' => 'show']);
    Route::resource('users', 'UsersController', ['except' => 'show']);
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);

    Route::get('files/delete/{id}', ['as' => 'deleteFile', 'uses' => 'FilesController@delete']);

    Route::get('statistic', ['as' => 'statistic', 'uses' => 'StatisticController@index']);
    Route::get('statistic/{post}', ['as' => 'statistic.show', 'uses' => 'StatisticController@show']);
});

app/Http/Controllers/CategoriesController.php
<?php namespace App\Http\Controllers;

use App\Ck\Models\Article;
use App\Ck\Models\Category;
use App\Ck\Requests\CategoryRequest;

class CategoriesController extends Controller
{

    public function __construct()
    {
        parent::__construct();
        view()->share('active', 'categories');
    }

    public function index()
    {
        view()->share('view', 'categories-list');

        $items = Category::where('parent_id', 0)->orderBy('ordering', 'ASC')->get();
        return View('categories.index', compact('items'));
    }

    public function create()
    {
        view()->share('view', 'categories-create');

        $item = new Category();
        return View('categories.form', compact('item'));
    }

    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return redirect('categories');
    }

    public function edit($id)
    {
        view()->share('view', 'categories-edit');

        $item = Category::find($id);
        return View('categories.form', compact('item'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $item = Category::find($id);
        $item->update($request->all());
        return redirect('categories');
    }

    public function show($id)
    {
        if (Article::whereState(1)->where('category_id', $id)->count() != 1) {
            view()->share('view', 'category-articles');
            view()->share('active', 'category'.$id);

            $items = Article::whereState(1)->where('category_id', $id)->orderBy('created_at', 'DESC')->paginate(20);

            return View('categories.show', compact('id', 'items'));
        } else {
            return redirect('article/'.Article::where('category_id', $id)->first()->id);
        }

    }

    public function destroy($id)
    {
        $item = Category::find($id);

        if (($item->children()->count() > 0) || ($item->articles()->count() > 0)) {
            return redirect()->back()->withErrors([0 => trans('messages.category_delete_fail')]);
        }

        $item->delete();

        return redirect()->back();
    }

    public function up($id)
    {
        $currentCategory = Category::find($id);
        if ($currentCategory->ordering > 1) {
            $tempCategory = Category::whereOrdering(($currentCategory->ordering - 1))->first();
            $tempCategory->ordering = $tempCategory->ordering + 1;
            $tempCategory->save();
            $currentCategory->ordering = $currentCategory->ordering - 1;
            $currentCategory->save();
        }
        return redirect()->back();
    }

    public function down($id)
    {
        $currentCategory = Category::find($id);
        $tempCategory = Category::whereOrdering(($currentCategory->ordering + 1))->first();
        if ($tempCategory) {
            $currentCategory->ordering = $currentCategory->ordering + 1;
            $currentCategory->save();
            $tempCategory->ordering = $tempCategory->ordering - 1;
            $tempCategory->save();
        }
        return redirect()->back();
    }

}

resources/views/categories/form.blade.php
<?php
if ($item->id) {
    $categories = \App\Ck\Models\Category::where('parent_id', '=', 0)->where('id', '!=', $item->id)->lists('title', 'id')->all();
} else {
    $categories = \App\Ck\Models\Category::where('parent_id', '=', 0)->lists('title', 'id')->all();
}
?>
@extends('layouts.main')
@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            @if ($item->id)
                {!! Form::model($item, ['route' => ['categories.update', $item->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
            @else
                {!! Form::model($item, ['route' => 'categories.store', 'class' => 'form-horizontal']) !!}
            @endif
                <div id="vue-app" class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            {!! Form::label('title', trans('labels.title'), ['class' => 'col-md-2 control-label']) !!}
                            <div class="col-md-10">
                                {!! Form::text('title', $item->title, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('parent_id', trans('labels.parent_category'), ['class' => 'col-md-2 control-label']) !!}
                            <div class="col-md-10">
                                <select v-model="selected" name="parent_id" class="form-control">
                                    <option value="0">{{ trans('labels.root_category') }}</option>
                                    @foreach ($categories as $id => $title)
                                        <option value="{{ $id }}" {{ ($id == $item->parent_id)?' selected':'' }}>{{ $title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group" v-show="selected == 0">
                            {!! Form::label('icon', trans('labels.icon'), ['class' => 'col-md-2 control-label']) !!}
                            <div class="col-md-10">
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-user') }" v-on:click.prevent="changeIcon('icon-user')"><i class="icon-user"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-people') }" v-on:click.prevent="changeIcon('icon-people')"><i class="icon-people"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-phone') }" v-on:click.prevent="changeIcon('icon-phone')"><i class="icon-phone"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-map') }" v-on:click.prevent="changeIcon('icon-map')"><i class="icon-map"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-location-pin') }" v-on:click.prevent="changeIcon('icon-location-pin')"><i class="icon-location-pin"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-direction') }" v-on:click.prevent="changeIcon('icon-direction')"><i class="icon-direction"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-directions') }" v-on:click.prevent="changeIcon('icon-directions')"><i class="icon-directions"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-compass') }" v-on:click.prevent="changeIcon('icon-compass')"><i class="icon-compass"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-layers') }" v-on:click.prevent="changeIcon('icon-layers')"><i class="icon-layers"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-list') }" v-on:click.prevent="changeIcon('icon-list')"><i class="icon-list"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-clock') }" v-on:click.prevent="changeIcon('icon-people')"><i class="icon-clock"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-notebook') }" v-on:click.prevent="changeIcon('icon-notebook')"><i class="icon-notebook"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-energy') }" v-on:click.prevent="changeIcon('icon-energy')"><i class="icon-energy"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-speedometer') }" v-on:click.prevent="changeIcon('icon-speedometer')"><i class="icon-speedometer"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-hourglass') }" v-on:click.prevent="changeIcon('icon-hourglass')"><i class="icon-hourglass"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-wallet') }" v-on:click.prevent="changeIcon('icon-wallet')"><i class="icon-wallet"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-speech') }" v-on:click.prevent="changeIcon('icon-speech')"><i class="icon-speech"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-puzzle') }" v-on:click.prevent="changeIcon('icon-puzzle')"><i class="icon-puzzle"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-pin') }" v-on:click.prevent="changeIcon('icon-pin')"><i class="icon-pin"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-handbag') }" v-on:click.prevent="changeIcon('icon-handbag')"><i class="icon-handbag"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-graduation') }" v-on:click.prevent="changeIcon('icon-graduation')"><i class="icon-graduation"></i></a>
                                <a href="#" class="btn btn-white waves-effect" v-bind:class="{'btn-default': isActive('icon-badge') }" v-on:click.prevent="changeIcon('icon-badge')"><i class="icon-badge"></i></a>
                                {!! Form::hidden('icon', $item->icon, ['v-model' => 'icon']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">
                                {!! Form::button(trans('buttons.save'), ['type' => 'submit', 'class' => 'btn btn-primary']) !!}
                                {!! link_to_route('categories.index', trans('buttons.close'), null, ['class' => 'btn btn-danger']) !!}
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection
@section('scripts')
    {!! Html::script('js/vue.js') !!}
    <script type="text/javascript">
        new Vue({
            el: '#vue-app',
            data: {
                selected: 0,
                icon: ''
            },
            methods: {
                "changeIcon": function(id) {
                    this.icon = id;
                },
                "isActive": function(id) {
                    return (this.icon == id);
                }
            }
        });
    </script>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12 text-xs-center text-right">
                        <a href="{{ route('categories.create') }}" class="btn btn-primary"><i
                                    class="fa fa-plus"></i> {{ trans('buttons.new') }}</a>
                    </div>
                    <div class="col-sm-12 table-responsive m-t-20">
                        <table class="table table-bordered table-hover m-0">
                            <tr>
                                <th>{{ trans('labels.title') }}</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                            @forelse($items as $i => $item)
                                <tr>
                                    <td>{{ $item->title }}</td>
                                    <td width="1%" nowrap class="text-center">
                                        @if ($i > 0)
                                            <a href="{{ url('categories/up/'.$item->id) }}"><i class="fa fa-toggle-up"></i></a>
                                        @endif
                                        @if ($i + 1 < count($items))
                                            <a href="{{ url('categories/down/'.$item->id) }}"><i class="fa fa-toggle-down"></i></a>
                                        @endif
                                    </td>
                                    <td width="1%" nowrap>
                                        <a href="{!! route('categories.edit', ['id' => $item->id]) !!}"><i
                                                    class="fa fa-edit"></i></a>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="#" data-href="{!! route('deleteCategory', ['id' => $item->id]) !!}"
                                           data-toggle="modal" data-target="#confirm-delete"><i
                                                    class="fa fa-remove"></i></a>
                                    </td>
                                </tr>
                                @foreach($item->children() as $child)
                                    <tr>
                                        <td>-- {{ $child->title }}</td>
                                        <td></td>
                                        <td width="1%" nowrap>
                                            <a href="{!! route('categories.edit', ['id' => $child->id]) !!}"><i
                                                        class="fa fa-edit"></i></a>
                                        </td>
                                        <td width="1%" nowrap class="text-center">
                                            <a href="#" data-href="{!! route('deleteCategory', ['id' => $child->id]) !!}"
                                               data-toggle="modal" data-target="#confirm-delete"><i
                                                        class="fa fa-remove"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            @empty
                                <tr>
                                    <td colspan="3">{{ trans('messages.list_empty') }}</td>
                                </tr>
                            @endforelse
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-sm" id="confirm-delete" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    {{ trans('messages.delete_confirmation') }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">{{ trans('buttons.no') }}</button>
                    <a class="btn btn-danger btn-ok">{{ trans('buttons.yes') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#confirm-delete').on('show.bs.modal', function (e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.main')
@section('content')
    <?php $user_id = Auth::user()->id; ?>
    <div class="row" style="max-width: 620px;">
        @forelse($items as $item)
            <div class="card-box p-0">
                {!! ImageHelper::feedImage($item->image) !!}
                <div class="text-center relative post-teaser">
                    <h2 class="post-title">{{ $item->title }}</h2>
                    <h4 class="post-lead">{!! str_replace("\r\n", "<br />", $item->lead) !!}</h4>
                    <a href="{{ url('article/'.$item->id) }}"
                       class="btn btn-primary">{{ trans('buttons.readmore') }}</a>
                </div>
            </div>
        @empty
            @if ($id == 12)
                @include('forms.form1')
            @elseif ($id == 15)
                @include('forms.form2')
            @else
                <div class="card-box">
                    <p class="m-b-0">{{ trans('messages.category_no_articles') }}</p>
                </div>
            @endif
        @endforelse
    </div>
@endsection