app/Http/routes.php
<?php

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('reset/sent', function () {
    return View('auth.sent');
});

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => 'auth'], function () {
    Route::any('/profile/remove', ['as' => 'removeAvatar', 'uses' => 'UsersController@removeAvatar']);

    Route::get('/', 'HomeController@getFeed');
    Route::get('/home/{filter}/{param?}', 'HomeController@getFeed');

    Route::post('form1', ['as' => 'form1', 'uses' => 'FormsController@form1']);
    Route::post('form2', ['as' => 'form2', 'uses' => 'FormsController@form2']);

    Route::get('group/{id}', 'HomeController@getGroup');
    Route::get('category/{id}', ['as' => 'category', 'uses' => 'CategoriesController@show']);
    Route::get('ajax/tags', 'Ajax\TagsController@getList');

    Route::get('search', 'SearchController@search');

    Route::resource('posts', 'PostsController', ['except' => 'destroy']);
    Route::get('posts/read/{id}', 'PostsController@read');
    Route::get('posts/star/{id}', 'PostsController@star');
    Route::post('comment', 'PostsController@comment');
    Route::get('comments/delete/{id}', 'PostsController@deleteComment');

    Route::get('profile', 'UsersController@getProfile');
    Route::post('profile', 'UsersController@postProfile');

    Route::get('article/{id}', ['as' => 'article', 'uses' => 'ArticlesController@show']);
    Route::get('articles/deleteImage/{id}', 'ArticlesController@deleteImage');
    Route::get('posts/deleteImage/{id}', 'PostsController@deleteImage');
    Route::any('posts/deleteown/{id}', 'PostsController@delete');

    Route::get('support', function () {
        view()->share('view', 'support');
        view()->share('active', 'support');

        return View('pages.support');
    });

    Route::get('files/download/{id}', ['as' => 'downloadFile', 'uses' => 'FilesController@download']);
});

Route::group(['prefix' => 'ajax', 'middleware' => 'auth'], function () {
    Route::post('post', 'Ajax\PostsController@create');
    Route::post('uploadImage', 'Ajax\FileController@uploadImage');
    Route::post('uploadFile', 'Ajax\FileController@uploadFile');
});

Route::group(['middleware' => ['auth', 'auth.admin']], function () {
    Route::any('posts/delete/{id}', ['as' => 'deletePost', 'uses' => 'PostsController@destroy']);
    Route::any('users/delete/{id}', ['as' => 'deleteUser', 'uses' => 'UsersController@destroy']);
    Route::any('tags/delete/{id}', ['as' => 'deleteTag', 'uses' => 'TagsController@destroy']);
    Route::any('categories/delete/{id}', ['as' => 'deleteCategory', 'uses' => 'CategoriesController@destroy']);
    Route::any('categories/up/{id}', ['as' => 'upCategory', 'uses' => 'CategoriesController@up']);
    Route::any('categories/down/{id}', ['as' => 'downCategory', 'uses' => 'CategoriesController@down']);
    Route::any('articles/delete/{id}', ['as' => 'deleteArticle', 'uses' => 'ArticlesController@destroy']);

    Route::resource('articles', 'ArticlesController', ['except' => 'show']);
    Route::resource('branches', 'BranchesController', ['except' => 'show']);
    Route::resource('groups', 'GroupsController', ['except' => 'show']);
    Route::resource('tags', 'TagsController', ['except' => 'show']);
    Route::resource('users', 'UsersController', ['except' => 'show']);
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);

    Route::get('files/delete/{id}', ['as' => 'deleteFile', 'uses' => 'FilesController@delete']);

    Route::get('statistic', ['as' => 'statistic', 'uses' => 'StatisticController@index']);
    Route::get('statistic/{post}', ['as' => 'statistic.show', 'uses' => 'StatisticController@show']);
});

app/Http/Controllers/ArticlesController.php
<?php namespace App\Http\Controllers;

use App\Ck\Models\Article;
use App\Http\Requests\ArticleRequest;
use Illuminate\Support\Facades\Storage;

class ArticlesController extends Controller
{

    public function __construct()
    {
        parent::__construct();
        view()->share('active', 'articles');
    }

    public function index()
    {
        view()->share('view', 'articles-list');

        $items = Article::orderBy('created_at', 'DESC')->paginate(20);

        return view('articles.index', compact('items'));
    }

    public function create()
    {
        view()->share('view', 'articles-create');

        $item = new Article();
        return View('articles.form', compact('item'));
    }

    public function store(ArticleRequest $request)
    {
        $data = $request->all();

        $data['state'] = isset($data['state']) ? 1 : 0;

        $item = Article::create($data);

        if (!empty($request->input('image'))) {
            $image = $request->input('image');
            Storage::move('temp/'.$image, 'images/'.$image);
        }

        foreach ($request->input('files', []) as $file) {
            \App\Ck\Models\File::find($file)->update(['article_id' => $item->id]);
        }

        if (!isset($data['tags'])) {
            $data['tags'] = array();
        }

        $item->tags()->sync($data['tags']);

        return redirect('articles');
    }

    public function edit($id)
    {
        view()->share('view', 'articles-edit');

        $item = Article::find($id);
        return View('articles.form', compact('item'));
    }

    public function update(ArticleRequest $request, $id)
    {
        $item = Article::find($id);
        $data = $request->all();

        $data['state'] = isset($data['state']) ? 1 : 0;

        if ($item->image != $request->input('image')) {
            $new_image = $request->input('image');
            Storage::move('temp/'.$new_image, 'images/'.$new_image);
            if (!empty($item->image) && Storage::has('images/'.$item->image)) {
                Storage::delete('images/'.$item->image);
            }
        }

        $item->update($data);

        foreach ($request->input('files', []) as $file) {
            \App\Ck\Models\File::find($file)->update(['article_id' => $item->id]);
        }

        if (!isset($data['tags'])) {
            $data['tags'] = array();
        }

        $item->tags()->sync($data['tags']);

        return redirect('articles');
    }

    public function show($id)
    {
        view()->share('view', 'article');

        $item = Article::findOrFail($id);

        if (isset($item->category_id)) {
            view()->share('active', 'category'.$item->category_id);
        }

        if ($item->state != 1) {
            return View('articles.notfound');
        }

        return View('articles.show', compact('item'));
    }

    public function read($id)
    {
        $user = \Auth::user();
        $item = Article::find($id);

        if (!$item->read->contains($user->id)) {
            $item->read()->attach($user->id);
        }

        return redirect()->back();
    }

    public function destroy($id)
    {
        Article::find($id)->delete();
        return redirect()->back();
    }

    public function deleteImage($id)
    {
        $item = Article::find($id);

        if (!empty($item->image)) {
            if (Storage::has('images/'.$item->image)) {
                Storage::delete('images/'.$item->image);
            }
            $item->image = null;
            $item->save();
        }

        return redirect('articles/'.$item->id.'/edit');
    }

}

resources/views/articles/form.blade.php
@extends('layouts.main')
@section('content')
    <div class="row" style="max-width: 940px;">
        <div class="col-sm-12">
            <div class="card-box">
                @if ($item->id)
                    {!! Form::model($item, ['route' => ['articles.update', $item->id], 'method' => 'PUT']) !!}
                @else
                    {!! Form::model($item, ['route' => 'articles.store']) !!}
                @endif
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            {!! Form::label('category_id', trans('labels.category'), ['class' => 'control-label']) !!}
                            <select name="category_id" id="category_id" class="form-control">
                                <option>{{ trans('labels.select_category') }}</option>
                                @foreach(DataHelper::categories() as $parent_id => $parent)
                                    @if ($parent['has_children'])
                                        <option disabled="disabled">{{ $parent['title'] }}</option>
                                        @foreach ($parent['children'] as $child_id => $child)
                                            <option value="{{ $child_id }}"{{ ($item->category_id == $child_id)?' selected="selected"':'' }}>
                                                -- {{ $child['title'] }}</option>
                                        @endforeach
                                    @else
                                        <option value="{{ $parent_id }}"{{ ($item->category_id == $parent_id)?' selected="selected"':'' }}>{{ $parent['title'] }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="pull-right m-t-30">
                                {!! Form::label('state', trans('labels.published'), ['class' => 'control-label', 'style' => 'margin-right: 30px;']) !!}
                                {!! Form::checkbox('state', 1, ($item->state == 1 || empty($item->state)), ['data-plugin' => 'switchery', 'data-color' => '#81c868', 'data-switchery' => 'true']) !!}
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            {!! Form::label('lead', trans('labels.image'), ['class' => 'control-label']) !!}
                            <div class="row">
                                @if (!empty($item->image))
                                    <div class="col-md-4">
                                        {!! ImageHelper::previewImage($item->image) !!}
                                        <a href="{{ url('articles/deleteImage/'.$item->id) }}" class="btn btn-danger m-t-10"><i class="fa fa-remove"></i> {{ trans('buttons.delete_image') }}</a>
                                    </div>
                                    <div class="col-md-8">
                                        <div id="imageUploader" class="dropzone"></div>
                                        {!! Form::hidden('image') !!}
                                    </div>
                                @else
                                    <div class="col-md-12">
                                        <div id="imageUploader" class="dropzone"></div>
                                        {!! Form::hidden('image') !!}
                                    </div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('title', trans('labels.title'), ['class' => 'control-label']) !!}
                            {!! Form::text('title', $item->title, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('lead', trans('labels.lead'), ['class' => 'control-label']) !!}
                            {!! Form::textarea('lead', $item->lead, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('content', trans('labels.content'), ['class' => 'control-label']) !!}
                            {!! Form::textarea('content', $item->content, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('lead', trans('labels.files'), ['class' => 'control-label']) !!}
                            <div id="fileUploader" class="dropzone"></div>
                            <div id="files-list">
                                @if (count($item->files))
                                    <ul class="list-group m-t-10">
                                        @foreach($item->files as $file)
                                            <li class="list-group-item">
                                                <a href="{{ url('files/delete/' . $file->id) }}" class="badge badge-danger"><i class="fa fa-remove"></i></a>
                                                <a href="{{ url('files/download/' . $file->id) }}">{{ $file->original }}</a>
                                            </li>
                                        @endforeach
                                    </ul>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="tags" class="control-label">{{ trans('labels.tags') }}</label>
                            <select id="tags" name="tags[]" class="select2 select2-multiple form-control" multiple="multiple">
                                @foreach(App\Ck\Models\Tag::all() as $tag)
                                    <option value="{{ $tag->id }}"{{ $item->tags->contains($tag->id)?' selected="selected"':'' }}>{{ $tag->title }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            {!! Form::hidden('id') !!}
                            {!! Form::button(trans('buttons.save'), ['type' => 'submit', 'class' => 'btn btn-primary']) !!}
                            {!! link_to_route('articles.index', trans('buttons.close'), null, ['class' => 'btn btn-danger']) !!}
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection
@section('styles')
    {!! Html::style('css/form.css') !!}
    {!! Html::style('css/editor.css') !!}
    {!! Html::style('css/dropzone.css') !!}
@endsection
@section('scripts')
    {!! Html::script('js/form.js') !!}
    {!! Html::script('js/editor.js') !!}
    {!! Html::script('js/dropzone.js') !!}
    <script type="text/javascript">
        $(document).ready(function () {

            $(".select2").select2({
                width: 'resolve'
            });

            $('#content').trumbowyg();

            Dropzone.options.imageUploader = {
                paramName: 'upload-image',
                url: "{{ url('ajax/uploadImage') }}",
                maxFilesize: 10,
                maxFiles: 1,
                dictDefaultMessage: '{{ trans('messages.upload_text') }}',
                acceptedFiles: 'image/*',
                init: function () {
                    this.on('success', function (file, resp) {
                        $('[name="image"]').val(resp.filename);
                    });
                    this.on('maxfilesexceeded', function (file) {
                        this.removeAllFiles();
                        this.addFile(file);
                    });
                },
                complete: function (file) {
                    if (file.size > 10*1024*1024) {
                        alert('File is larger than 5Mb');
                        return false;
                    }
                    if (!file.type.match('image.*')) {
                        alert('Only images are allowed for this field.');
                        return false;
                    }
                }
            };

            Dropzone.options.fileUploader = {
                paramName: 'upload-file',
                url: "{{ url('ajax/uploadFile') }}",
                maxFilesize: 100,
                dictDefaultMessage: '{{ trans('messages.upload_text2') }}',
                init: function () {
                    this.on('success', function (file, resp) {
                        $('#files-list').append('<input type="checkbox" name="files[]" class="hidden" value="'+resp.id+'" checked="checked" />');
                    });
                },
                complete: function(file) {
                    if (file.size > 100*1024*1024) {
                        alert('File is larger than 100Mb');
                        return false;
                    }
                }
            };

        });
    </script>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <a href="{{ route('articles.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> {{ trans('buttons.new') }}</a>
                    </div>
                    <div class="col-sm-12 table-responsive m-t-20">
                        <table class="table table-bordered table-hover m-0">
                            <tr>
                                <th>{{ trans('labels.title') }}</th>
                                <th>{{ trans('labels.category') }}</th>
                                <th>{{ trans('labels.author') }}</th>
                                <th>{{ trans('labels.created') }}</th>
                                <th class="uk-text-center">{{ trans('labels.status') }}</th>
                                <th>{{ trans('labels.edit') }}</th>
                                <th>{{ trans('labels.delete') }}</th>
                            </tr>
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ @$item->category->title }}</td>
                                    <td>{{ @$item->author->name }}</td>
                                    <td>{{ $item->created_at }}</td>
                                    <td class="uk-text-center" width="1%" nowrap>
                                        <div class="label label-{{ ($item->state == 1)?'default':'pink' }}">{{ ($item->state == 1)?trans('labels.published'):trans('labels.unpublished') }}</div>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="{!! route('articles.edit', ['id' => $item->id]) !!}"><i class="fa fa-edit"></i></a>
                                    </td>
                                    <td width="1%" nowrap class="text-center">
                                        <a href="#" data-href="{!! route('deleteArticle', ['id' => $item->id]) !!}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-remove"></i></a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7">{{ trans('messages.list_empty') }}</td>
                                </tr>
                            @endforelse
                        </table>
                    </div>
                    <div class="col-sm-12 text-center">
                        {!! $items->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-sm" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    {{ trans('messages.delete_confirmation') }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('buttons.no') }}</button>
                    <a class="btn btn-danger btn-ok">{{ trans('buttons.yes') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#confirm-delete').on('show.bs.modal', function(e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
@endsection

resources/views/articles/notfound.blade.php
@extends('layouts.main')
@section('content')
    <div class="row" style="max-width: 934px;">
        <div class="col-md-12">
            <div class="card-box p-0">
                <article style="text-align: center; padding: 70px 50px;">
                    <h1>Beklager. Artikkelen eller innlegget du leter etter er slettet eller avpublisert.</h1>
                    <a href="{{ url('/') }}">Gå til forsiden.</a>
                </article>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.main')
@section('content')
    <?php $user_id = Auth::user()->id; ?>
    <div class="row" style="max-width: 934px;">
        <div class="col-md-12">
            <div class="card-box p-0">
                <article>
                    @if(!empty($item->image))
                        {!! ImageHelper::responsiveImage($item->image) !!}
                    @endif
                    <div class="relative article-container">
                        <h1 class="article-title">{{ $item->title }}</h1>
                        <h3 class="article-lead">{!! prepareLead($item->lead) !!}</h3>
                        <div class="article-content">
                            {!! prepareContent($item->content) !!}
                        </div>
                        <a href="#" class="btn btn-back"><i class="fa fa-angle-double-left"></i> {{ trans('buttons.back') }}</a>
                    </div>
                </article>
            </div>
            @if (count($item->files))
                <h4><i class="fa fa-download"></i> {{ trans('labels.files') }}</h4>
                <div class="card-box">
                    <ul class="list-group m-b-0">
                        @foreach($item->files as $file)
                            <li class="list-group-item">
                                <a href="{{ url('files/download/' . $file->id) }}">{{ $file->original }}</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
    </div>
@endsection